### ISSUE TITLE
Documents Adder

### ISSUE THREAD

**Issue by livrasand** [Miaosi001/JWLibrary-VideosAdder#1]
It would be super cool to have one to add our own documents, especially the accounting ones. It would save me a lot of work. Do you have something like that?

**Comment by darioragusa** [comment]
Hi, unfortunately no, but I think it's worth a try when I find some free time

**Comment by livrasand** [comment]
Yes please, it would be great to have this function, I have worked with *.jwpub files, I can edit them but not their content. When opening the database I find a BLOB content, which is encrypted. Maybe you can add, instead of modifying that existing BLOB, add a new one without modifying it. It's just a crazy idea, however you are the professional.

**Comment by darioragusa** [comment]
So, if I understood correctly, you would like to edit the blob field. Basically an app in which you put the text and can encode or decode it.

**Comment by livrasand** [comment]
Yes correct, I can show you so far what I have discovered from *.jwpub files. And based on that maybe you can do something. It seems that there is a way to export that BLOB through SQLite Browser to a *.bin file, then with some program they decrypt the file and convert it to *.htm. With the help of Sigil, they edit the *.htm file, and again do the process in reverse to insert it back into the table. A *.jwpub is composed of two files inside, 1) "manifest.json", which contains the necessary information so that JW Library can read the *.jwpub file, and 2) a compressed file called "contents". Inside "contents" we find a *.db database, if the *.jwpub contains images, inside the compressed "contents" the images will be found.

**Comment by darioragusa** [comment]
If you haven't seen it, we discussed about this [here](https://github.com/darioragusa/JW-Library-macOS/issues/1). I managed to get the content, but I didn't try doing the opposite.

**Comment by livrasand** [comment]
Wow! You are a CRACK! Thank you very much, I will read the whole conversation
