### ISSUE TITLE
Multimedia section instead downloaded section

### ISSUE THREAD

**Issue by joshdejuan** [Miaosi001/JWLibrary-VideosAdder#2]
Is it possible for the video to appear in the multimedia section of the meeting itself instead of the downloaded section?

**Comment by darioragusa** [comment]
Yes, it's possible. You can find them in the Watchtower of the current week. Let me know if there are any problems.

**Comment by joshdejuan** [comment]
Thanks for the new version 1.0.1. Now I see the video in the **Watchtower** section. But can it be also in the **LIFE AND MINISTRY MEETING** section and do it in the **ImageAdder**? Thank you so much for this work.

**Comment by darioragusa** [comment]
It can also be done, but I'm planning to do this on a new app that merge the existing ones by inserting both images and videos

**Comment by joshdejuan** [comment]
Great! Please let me know when you release the first version. Thanks.

**Comment by darioragusa** [comment]
Hi, you can find the new app [here](https://github.com/darioragusa/JWLibrary-MediaInserter)
