### ISSUE TITLE
Error in command "AddVideo"

### ISSUE THREAD

**Issue by livrasand** [Miaosi001/JWLibrary-VideosAdder#3]
I find myself copying your program, to implement it in Attendant Zoom, but for some reason it gives me the following error, I think it is necessary to declare it. If I declare it, it gives me the following code:

```
Private Sub AddVideo(dbDir As String, docID As Integer, collectionDir As String, vidList As List(Of String))
        Throw New NotImplementedException()
End Sub
```

![Captura de pantalla (378)](https://user-images.githubusercontent.com/104039397/169082324-4e938bd7-a7c9-4b9f-9136-82d588294962.png)

**Comment by darioragusa** [comment]
AddVideo is defined [here](https://github.com/darioragusa/JWLibrary-VideosAdder/blob/82c0aa4b5f27f48d91af9e3c41933e4e4c3b1a44/JWLibrary-VideosAdder/AddVideos.vb)

**Comment by livrasand** [comment]
LOL! Thanks a lot, I have unified your three applications in one, you can find it in the future in my free app Attendant Zoom 2022 Summer Edition in the "JW Library" tab.
